### ISSUE TITLE
Disabling Whispers

### ISSUE THREAD

**Issue by philipgray** [tomaarsen/TwitchMarkovChain#5]
Is it possible to disable whispers or the possibility for a setting to turn them off? 

I've been fiddling with it for a while but I'm not having any luck disabling whispers which is getting the bot shadowbanned from Twitch.

**Comment by CubieDev** [comment]
This is not currently possible, although I will consider this as a potential future feature. 
You may comment out lines [131](https://github.com/CubieDev/TwitchMarkovChain/blob/master/MarkovChainBot.py#L131) and [132](https://github.com/CubieDev/TwitchMarkovChain/blob/master/MarkovChainBot.py#L132) in `MarkovChainBot.py`, which will prevent cooldown whispers.

I realise this is a bit of a non-solution, but might help for the time being.

**Comment by philipgray** [comment]
This is perfect for me! For whatever reason I completely overlooked those lines when I was trying to figure it out. I'm almost embarrassed to admit that!!

**Comment by CubieDev** [comment]
Another alternative I just thought of is to put the cooldown message in chat instead of letting the user know via whispers. 
To do this you can comment out line [131](https://github.com/CubieDev/TwitchMarkovChain/blob/master/MarkovChainBot.py#L131), then unindent line [132](https://github.com/CubieDev/TwitchMarkovChain/blob/master/MarkovChainBot.py#L132), replace `self.ws.send_whisper(m.user, ` with `self.ws.send_message(`, and lastly removing ` !nopm to stop these cooldown pm's.` from the string that's sent.

I'll put an option to switch between not displaying the cooldown, whispering the cooldown or posting it in chat on my TODO list.
